### ISSUE TITLE
Call stack safety

### ISSUE THREAD

**Issue by paluh** [spacchetti/purescript-docs-search#8]
Hi!

Thanks for building and sharing this useful tool!

I'm getting `RangeError: Maximum call stack size exceeded` for a quite large project. I'm using `purs` version `0.13.0` at the moment but I'm not sure if this is relevant.
Here is a short stack trace and attached bundle:

```
[nix-shell:~/programming/purescript/projects/magusai]$ purescript-docs-search build-index                                                                             
Building the search index...
Found 1071 modules.
/home/paluh/programming/purescript/projects/magusai/node_modules/purescript-docs-search/dist/main.js:2317                                                             
      function Cons(value0, value1) {
                   ^

RangeError: Maximum call stack size exceeded
    at new Cons (/home/paluh/programming/purescript/projects/magusai/node_modules/purescript-docs-search/dist/main.js:2317:20)                                        
    at $tco_loop (/home/paluh/programming/purescript/projects/magusai/node_modules/purescript-docs-search/dist/main.js:11934:89)                                      
    at /home/paluh/programming/purescript/projects/magusai/node_modules/purescript-docs-search/dist/main.js:11998:33                                                  
    at Object.shapeOfType (/home/paluh/programming/purescript/projects/magusai/node_modules/purescript-docs-search/dist/main.js:12003:97)                             
    at /home/paluh/programming/purescript/projects/magusai/node_modules/purescript-docs-search/dist/main.js:12047:85                                                  
    at /home/paluh/programming/purescript/projects/magusai/node_modules/purescript-docs-search/dist/main.js:12054:58                                                  
    at /home/paluh/programming/purescript/projects/magusai/node_modules/purescript-docs-search/dist/main.js:2608:59                                                   
    at /home/paluh/programming/purescript/projects/magusai/node_modules/purescript-docs-search/dist/main.js:2608:110                                                  
    at /home/paluh/programming/purescript/projects/magusai/node_modules/purescript-docs-search/dist/main.js:2608:110                                                  
    at /home/paluh/programming/purescript/projects/magusai/node_modules/purescript-docs-search/dist/main.js:2608:110
```

[dist.main.js.zip](https://github.com/spacchetti/purescript-docs-search/files/3421177/dist.main.js.zip)

Please ping me back if you want me to test or provide additional info.

**Comment by klntsky** [comment]
Thank you for the report. I believe [this function](https://github.com/spacchetti/purescript-docs-search/blob/c3d51d6105e981b8ff4db06cb793c77b6d477b9a/src/Docs/Search/TypeIndex.purs#L52) was the culprit (at least I was able to reproduce a stackoverflow by limiting the `--stack_size`).

I'll release [a fix](https://github.com/spacchetti/purescript-docs-search/pull/9) in a few minutes.

**Comment by klntsky** [comment]
Released. Could you please check if it fixed the problem for you?

**Comment by paluh** [comment]
> Released. Could you please check if it fixed the problem for you?

Yeah! 0.0.3 fixes this issue. Thanks a lot!
